version: '3.8'

services:
  # Backend API com Socket.IO
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roi-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=https://roilabs.com.br
    ports:
      - "5000:5000"
    networks:
      - roi-network

  # Frontend (se quiser servir via Docker também)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roi-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - roi-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: roi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro  # Para certificados SSL
    depends_on:
      - backend
      - frontend
    networks:
      - roi-network

networks:
  roi-network:
    driver: bridge